const express =  require('express')
const router = express.Router()
const {productInfo} = require('../controller/product')
const {customerOrder} = require('../controller/product') 
const {customerTotalPayment} = require('../controller/product') 
const {productNameandOrderedNo} = require('../controller/product') 
const {getEmployeesWithoutCustomers} = require('../controller/product') 
const {getCustomersWithOrderCount} = require('../controller/product') 
const {getAveragePaymentAmount} = require('../controller/product') 
const {orderandorderdetails} = require('../controller/product') 
const {getUsaemployeesWithCustomer} = require('../controller/product') 
const {productOrderedByUsaCustomers} = require('../controller/product') 
const {getTotalRevenueByProductLine} = require('../controller/product') 
const {customerwhoplaceorder} = require('../controller/product') 
const {EmployeesAssosiatedWithCustomer} = require('../controller/product') 
const {ProductandProductLine} = require('../controller/product') 
const {CustomermadePayments} = require('../controller/product') 
const {EmployeeandOffice} = require('../controller/product') 
const {ProductLineandPayment} = require('../controller/product') 
const {updatePrices} = require('../controller/product') 


router.get('/productinfo',productInfo)
router.get('/customerorder',customerOrder)
router.get('/customertotalpayment',customerTotalPayment)
router.get('/productNameandOrderedNo',productNameandOrderedNo)
router.get('/getEmployeesWithoutCustomers',getEmployeesWithoutCustomers)
router.get('/getCustomersWithOrderCount',getCustomersWithOrderCount)
router.get('/getAveragePaymentAmount',getAveragePaymentAmount)
router.get('/orderandorderdetails',orderandorderdetails)
router.get('/getUsaemployeesWithCustomer',getUsaemployeesWithCustomer)
router.get('/productOrderedByUsaCustomers',productOrderedByUsaCustomers)
router.get('/getTotalRevenueByProductLine',getTotalRevenueByProductLine)
router.get('/customerwhoplaceorder',customerwhoplaceorder)
router.get('/EmployeesAssosiatedWithCustomer',EmployeesAssosiatedWithCustomer)
router.get('/ProductandProductLine',ProductandProductLine)
router.get('/CustomermadePayments',CustomermadePayments)
router.get('/EmployeeandOffice',EmployeeandOffice)
router.get('/ProductLineandPayment',ProductLineandPayment)
router.get('/updatePrices',updatePrices)




module.exports = {router}